 
MOBILITY_FACTOR_MIN = 0.1
MOBILITY_FACTOR_MAX =  0.9

INFECTION_RATE_FACTOR_MIN = 0.25
INFECTION_RATE_FACTOR_MAX = 0.9

MORTALITY_FACTOR_MIN = 0.1
MORTALITY_FACTOR_MAX = 0.3

SUSCEPTIBLE_BETA = 0.5
SIUSCEPTIBLE_DELTA = 0.1

INFECTECTION_DELTA = 0.0

RECOEVERD_DELTA = 0.0
